import Foundation
import ActorEdgeCore
import Distributed

/// Convenience methods for connecting to ActorEdge servers
public extension ActorEdgeSystem {
    /// Create a client system connected to the specified endpoint
    static func client(
        endpoint: String,
        tls: ClientTLSConfiguration? = nil
    ) async throws -> ActorEdgeSystem {
        let transport = try await GRPCActorTransport(endpoint, tls: tls)
        return ActorEdgeSystem(transport: transport)
    }
}

// Note: The $Protocol stubs generated by @Resolvable have their own resolve() methods
// We don't need to provide generic resolve() extensions